<?php
/**
 * Données des documents de l'application e-Archive
 * Simuler une base de données de documents
 */

return [
    'documents' => [
        [
            'id' => 1,
            'title' => 'Rapport annuel 2023',
            'description' => 'Rapport annuel détaillé des activités du SGITP pour l\'année 2023',
            'filename' => 'rapport_annuel_2023.pdf',
            'original_filename' => 'Rapport Annuel SGITP 2023.pdf',
            'file_type' => 'pdf',
            'file_size' => 2456789, // en bytes
            'mime_type' => 'application/pdf',
            'hash' => 'sha256:a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6',
            'status' => 'archived',
            'collection_id' => 1,
            'collection_name' => 'Rapports Annuels',
            'category' => 'Rapport',
            'tags' => ['rapport', 'annuel', '2023', 'sgitp'],
            'confidentiality' => 'public',
            'retention_period' => 10, // en années
            'created_by' => 2,
            'created_by_name' => 'Marie Dubois',
            'validated_by' => 1,
            'validated_by_name' => 'Benaja Bope',
            'created_at' => '2024-01-12 12:30:00',
            'validated_at' => '2024-01-12 14:15:00',
            'last_accessed' => '2024-01-12 15:20:00',
            'access_count' => 45,
            'version' => '1.0',
            'pages_count' => 156,
            'language' => 'fr'
        ],
        [
            'id' => 2,
            'title' => 'Contrat de construction - Pont de Kinshasa',
            'description' => 'Contrat de construction du nouveau pont reliant Kinshasa et Brazzaville',
            'filename' => 'contrat_pont_kinshasa_2024.pdf',
            'original_filename' => 'Contrat Construction Pont KIN-BZV 2024.pdf',
            'file_type' => 'pdf',
            'file_size' => 3789456,
            'mime_type' => 'application/pdf',
            'hash' => 'sha256:b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a1',
            'status' => 'pending',
            'collection_id' => 2,
            'collection_name' => 'Contrats Infrastructure',
            'category' => 'Contrat',
            'tags' => ['contrat', 'pont', 'infrastructure', 'kinshasa'],
            'confidentiality' => 'confidentiel',
            'retention_period' => 25,
            'created_by' => 3,
            'created_by_name' => 'Jean Malonga',
            'validated_by' => null,
            'validated_by_name' => null,
            'created_at' => '2024-01-12 09:45:00',
            'validated_at' => null,
            'last_accessed' => '2024-01-12 10:00:00',
            'access_count' => 12,
            'version' => '2.1',
            'pages_count' => 89,
            'language' => 'fr'
        ],
        [
            'id' => 3,
            'title' => 'Plan d\'urbanisme - Zone Nord',
            'description' => 'Plan directeur d\'urbanisme pour le développement de la zone nord de Kinshasa',
            'filename' => 'plan_urbanisme_zone_nord.dwg',
            'original_filename' => 'Plan Urbanisme Zone Nord KIN.dwg',
            'file_type' => 'dwg',
            'file_size' => 15678901,
            'mime_type' => 'application/acad',
            'hash' => 'sha256:c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a1b2',
            'status' => 'validated',
            'collection_id' => 3,
            'collection_name' => 'Plans d\'Urbanisme',
            'category' => 'Plan',
            'tags' => ['urbanisme', 'plan', 'zone-nord', 'kinshasa'],
            'confidentiality' => 'internal',
            'retention_period' => 50,
            'created_by' => 3,
            'created_by_name' => 'Pierre Durand',
            'validated_by' => 2,
            'validated_by_name' => 'Marie Dubois',
            'created_at' => '2024-01-11 16:20:00',
            'validated_at' => '2024-01-12 09:10:00',
            'last_accessed' => '2024-01-12 14:45:00',
            'access_count' => 28,
            'version' => '2.1',
            'pages_count' => 1,
            'language' => 'fr'
        ],
        [
            'id' => 4,
            'title' => 'Procédure de validation des documents',
            'description' => 'Document de procédure interne pour la validation des documents d\'archive',
            'filename' => 'procedure_validation_docs.docx',
            'original_filename' => 'Procédure Validation Documents V3.docx',
            'file_type' => 'docx',
            'file_size' => 456789,
            'mime_type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'hash' => 'sha256:d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a1b2c3',
            'status' => 'archived',
            'collection_id' => 4,
            'collection_name' => 'Procédures Internes',
            'category' => 'Procédure',
            'tags' => ['procédure', 'validation', 'interne', 'documentation'],
            'confidentiality' => 'internal',
            'retention_period' => 5,
            'created_by' => 1,
            'created_by_name' => 'Benaja Bope',
            'validated_by' => 4,
            'validated_by_name' => 'Sophie Martin',
            'created_at' => '2024-01-10 14:15:00',
            'validated_at' => '2024-01-11 10:30:00',
            'last_accessed' => '2024-01-12 11:20:00',
            'access_count' => 67,
            'version' => '3.0',
            'pages_count' => 24,
            'language' => 'fr'
        ],
        [
            'id' => 5,
            'title' => 'Budget prévisionnel 2024',
            'description' => 'Budget prévisionnel détaillé pour les activités 2024 du département infrastructure',
            'filename' => 'budget_previsionnel_2024.xlsx',
            'original_filename' => 'Budget Prévisionnel Infrastructure 2024.xlsx',
            'file_type' => 'xlsx',
            'file_size' => 789456,
            'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'hash' => 'sha256:e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a1b2c3d4',
            'status' => 'draft',
            'collection_id' => 5,
            'collection_name' => 'Budgets',
            'category' => 'Budget',
            'tags' => ['budget', 'prévisionnel', '2024', 'infrastructure'],
            'confidentiality' => 'confidential',
            'retention_period' => 7,
            'created_by' => 2,
            'created_by_name' => 'Marie Dubois',
            'validated_by' => null,
            'validated_by_name' => null,
            'created_at' => '2024-01-09 09:30:00',
            'validated_at' => null,
            'last_accessed' => '2024-01-12 08:15:00',
            'access_count' => 8,
            'version' => '0.5',
            'pages_count' => 15,
            'language' => 'fr'
        ],
        [
            'id' => 16,
            'title' => 'Facture équipement bureautique - Janvier 2024',
            'description' => 'Facture d\'achat d\'équipements informatiques et bureautiques pour le premier trimestre',
            'filename' => 'facture_equipement_jan2024.pdf',
            'original_filename' => 'Facture Equipement Bureau Q1-2024.pdf',
            'file_type' => 'pdf',
            'file_size' => 456789,
            'mime_type' => 'application/pdf',
            'hash' => 'sha256:f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a1b2c3d4e5',
            'status' => 'pending',
            'collection_id' => 5,
            'collection_name' => 'Finances et Comptabilité',
            'category' => 'Facture',
            'tags' => ['facture', 'équipement', 'bureautique', 'informatique'],
            'confidentiality' => 'interne',
            'retention_period' => 7,
            'created_by' => 5,
            'created_by_name' => 'Paul Kasongo',
            'validated_by' => null,
            'validated_by_name' => null,
            'created_at' => '2024-01-12 11:30:00',
            'validated_at' => null,
            'last_accessed' => '2024-01-12 11:45:00',
            'access_count' => 3,
            'version' => '1.0',
            'pages_count' => 8,
            'language' => 'fr'
        ],
        [
            'id' => 17,
            'title' => 'Demande de congé - Marie Dubois',
            'description' => 'Demande de congé annuel pour la période du 15 au 30 janvier 2024',
            'filename' => 'demande_conge_marie_dubois.pdf',
            'original_filename' => 'Demande Congé M.Dubois Jan2024.pdf',
            'file_type' => 'pdf',
            'file_size' => 234567,
            'mime_type' => 'application/pdf',
            'hash' => 'sha256:g7h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a1b2c3d4e5f6',
            'status' => 'pending',
            'collection_id' => 6,
            'collection_name' => 'Ressources Humaines',
            'category' => 'Demande',
            'tags' => ['congé', 'rh', 'personnel', 'demande'],
            'confidentiality' => 'personnel',
            'retention_period' => 5,
            'created_by' => 2,
            'created_by_name' => 'Marie Dubois',
            'validated_by' => null,
            'validated_by_name' => null,
            'created_at' => '2024-01-12 14:20:00',
            'validated_at' => null,
            'last_accessed' => '2024-01-12 14:25:00',
            'access_count' => 1,
            'version' => '1.0',
            'pages_count' => 2,
            'language' => 'fr'
        ],
        [
            'id' => 18,
            'title' => 'Plan d\'aménagement - Quartier Gombe',
            'description' => 'Plan détaillé d\'aménagement urbain pour le quartier Gombe, secteur résidentiel',
            'filename' => 'plan_amenagement_gombe.dwg',
            'original_filename' => 'Plan Aménagement Gombe 2024.dwg',
            'file_type' => 'dwg',
            'file_size' => 15678901,
            'mime_type' => 'application/acad',
            'hash' => 'sha256:h8i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a1b2c3d4e5f6g7',
            'status' => 'pending',
            'collection_id' => 3,
            'collection_name' => 'Plans et Schémas',
            'category' => 'Plan',
            'tags' => ['plan', 'aménagement', 'urbanisme', 'gombe'],
            'confidentiality' => 'public',
            'retention_period' => 30,
            'created_by' => 4,
            'created_by_name' => 'Sophie Kanza',
            'validated_by' => null,
            'validated_by_name' => null,
            'created_at' => '2024-01-12 16:45:00',
            'validated_at' => null,
            'last_accessed' => '2024-01-12 17:00:00',
            'access_count' => 7,
            'version' => '3.2',
            'pages_count' => null,
            'language' => 'fr'
        ],
        [
            'id' => 19,
            'title' => 'Rapport de mission - Inspection routes Kongo Central',
            'description' => 'Rapport d\'inspection des infrastructures routières dans la province du Kongo Central',
            'filename' => 'rapport_mission_kongo_central.docx',
            'original_filename' => 'Rapport Mission Routes KC 2024.docx',
            'file_type' => 'docx',
            'file_size' => 1234567,
            'mime_type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
            'hash' => 'sha256:i9j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a1b2c3d4e5f6g7h8',
            'status' => 'pending',
            'collection_id' => 4,
            'collection_name' => 'Rapports de Mission',
            'category' => 'Rapport',
            'tags' => ['rapport', 'mission', 'routes', 'kongo-central'],
            'confidentiality' => 'interne',
            'retention_period' => 15,
            'created_by' => 6,
            'created_by_name' => 'André Mutombo',
            'validated_by' => null,
            'validated_by_name' => null,
            'created_at' => '2024-01-12 08:15:00',
            'validated_at' => null,
            'last_accessed' => '2024-01-12 08:30:00',
            'access_count' => 2,
            'version' => '1.0',
            'pages_count' => 24,
            'language' => 'fr'
        ],
        [
            'id' => 20,
            'title' => 'Devis travaux réfection bureau direction',
            'description' => 'Devis détaillé pour les travaux de réfection du bureau de la direction générale',
            'filename' => 'devis_refection_bureau_direction.xlsx',
            'original_filename' => 'Devis Réfection Bureau DG 2024.xlsx',
            'file_type' => 'xlsx',
            'file_size' => 789123,
            'mime_type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'hash' => 'sha256:j0k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a1b2c3d4e5f6g7h8i9',
            'status' => 'pending',
            'collection_id' => 5,
            'collection_name' => 'Finances et Comptabilité',
            'category' => 'Devis',
            'tags' => ['devis', 'travaux', 'réfection', 'bureau'],
            'confidentiality' => 'confidentiel',
            'retention_period' => 10,
            'created_by' => 7,
            'created_by_name' => 'Claudine Mbuyi',
            'validated_by' => null,
            'validated_by_name' => null,
            'created_at' => '2024-01-12 13:20:00',
            'validated_at' => null,
            'last_accessed' => '2024-01-12 13:35:00',
            'access_count' => 5,
            'version' => '2.0',
            'pages_count' => null,
            'language' => 'fr'
        ],
        [
            'id' => 21,
            'title' => 'Procès-verbal réunion comité technique',
            'description' => 'PV de la réunion du comité technique du 10 janvier 2024 sur les projets d\'infrastructure',
            'filename' => 'pv_reunion_comite_technique_jan2024.pdf',
            'original_filename' => 'PV Réunion Comité Technique 10-01-2024.pdf',
            'file_type' => 'pdf',
            'file_size' => 567890,
            'mime_type' => 'application/pdf',
            'hash' => 'sha256:k1l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a1b2c3d4e5f6g7h8i9j0',
            'status' => 'pending',
            'collection_id' => 7,
            'collection_name' => 'Procès-verbaux',
            'category' => 'PV',
            'tags' => ['pv', 'réunion', 'comité', 'technique'],
            'confidentiality' => 'interne',
            'retention_period' => 8,
            'created_by' => 8,
            'created_by_name' => 'Daniel Lumumba',
            'validated_by' => null,
            'validated_by_name' => null,
            'created_at' => '2024-01-11 15:30:00',
            'validated_at' => null,
            'last_accessed' => '2024-01-11 16:00:00',
            'access_count' => 8,
            'version' => '1.0',
            'pages_count' => 6,
            'language' => 'fr'
        ],
        [
            'id' => 22,
            'title' => 'Certificat de conformité - Bâtiment administratif',
            'description' => 'Certificat de conformité aux normes de construction pour le nouveau bâtiment administratif',
            'filename' => 'certificat_conformite_batiment_admin.pdf',
            'original_filename' => 'Certificat Conformité Bât Admin 2024.pdf',
            'file_type' => 'pdf',
            'file_size' => 345678,
            'mime_type' => 'application/pdf',
            'hash' => 'sha256:l2m3n4o5p6q7r8s9t0u1v2w3x4y5z6a1b2c3d4e5f6g7h8i9j0k1',
            'status' => 'pending',
            'collection_id' => 8,
            'collection_name' => 'Conformité et Qualité',
            'category' => 'Certificat',
            'tags' => ['certificat', 'conformité', 'bâtiment', 'administratif'],
            'confidentiality' => 'public',
            'retention_period' => 20,
            'created_by' => 3,
            'created_by_name' => 'Jean Malonga',
            'validated_by' => null,
            'validated_by_name' => null,
            'created_at' => '2024-01-12 10:45:00',
            'validated_at' => null,
            'last_accessed' => '2024-01-12 11:00:00',
            'access_count' => 4,
            'version' => '1.0',
            'pages_count' => 4,
            'language' => 'fr'
        ]
    ],
    
    'collections' => [
        [
            'id' => 1,
            'name' => 'Rapports Annuels',
            'description' => 'Collection des rapports annuels du SGITP',
            'icon' => 'fa-chart-line',
            'color' => 'blue',
            'documents_count' => 5,
            'total_size' => 12456789,
            'created_at' => '2023-01-15 10:00:00',
            'last_updated' => '2024-01-12 14:15:00',
            'access_level' => 'public'
        ],
        [
            'id' => 2,
            'name' => 'Contrats Infrastructure',
            'description' => 'Contrats et accords pour les projets d\'infrastructure',
            'icon' => 'fa-handshake',
            'color' => 'green',
            'documents_count' => 23,
            'total_size' => 89456123,
            'created_at' => '2023-03-20 14:30:00',
            'last_updated' => '2024-01-12 08:45:00',
            'access_level' => 'restricted'
        ],
        [
            'id' => 3,
            'name' => 'Plans d\'Urbanisme',
            'description' => 'Plans directeurs et documents d\'urbanisme',
            'icon' => 'fa-city',
            'color' => 'purple',
            'documents_count' => 67,
            'total_size' => 234567890,
            'created_at' => '2023-02-10 09:15:00',
            'last_updated' => '2024-01-12 09:10:00',
            'access_level' => 'internal'
        ],
        [
            'id' => 4,
            'name' => 'Procédures Internes',
            'description' => 'Documentation des procédures et processus internes',
            'icon' => 'fa-cogs',
            'color' => 'yellow',
            'documents_count' => 34,
            'total_size' => 15678901,
            'created_at' => '2023-01-01 08:00:00',
            'last_updated' => '2024-01-11 10:30:00',
            'access_level' => 'internal'
        ],
        [
            'id' => 5,
            'name' => 'Budgets',
            'description' => 'Documents budgétaires et financiers',
            'icon' => 'fa-euro-sign',
            'color' => 'red',
            'documents_count' => 12,
            'total_size' => 9456789,
            'created_at' => '2023-04-01 11:20:00',
            'last_updated' => '2024-01-09 09:30:00',
            'access_level' => 'confidential'
        ],
        [
            'id' => 6,
            'name' => 'Finances et Comptabilité',
            'description' => 'Documents financiers, factures et devis',
            'icon' => 'fa-calculator',
            'color' => 'green',
            'documents_count' => 8,
            'total_size' => 2456789,
            'created_at' => '2023-01-15 14:30:00',
            'last_updated' => '2024-01-12 11:45:00',
            'access_level' => 'internal'
        ],
        [
            'id' => 7,
            'name' => 'Ressources Humaines',
            'description' => 'Documents RH, demandes et procédures personnel',
            'icon' => 'fa-users',
            'color' => 'blue',
            'documents_count' => 15,
            'total_size' => 1234567,
            'created_at' => '2023-02-01 09:00:00',
            'last_updated' => '2024-01-12 14:25:00',
            'access_level' => 'confidential'
        ],
        [
            'id' => 8,
            'name' => 'Rapports de Mission',
            'description' => 'Rapports d\'inspection et missions sur le terrain',
            'icon' => 'fa-map-marked-alt',
            'color' => 'orange',
            'documents_count' => 23,
            'total_size' => 5678901,
            'created_at' => '2023-03-10 10:15:00',
            'last_updated' => '2024-01-12 08:30:00',
            'access_level' => 'internal'
        ],
        [
            'id' => 9,
            'name' => 'Procès-verbaux',
            'description' => 'PV de réunions, comités et assemblées',
            'icon' => 'fa-gavel',
            'color' => 'purple',
            'documents_count' => 18,
            'total_size' => 1567890,
            'created_at' => '2023-01-05 08:30:00',
            'last_updated' => '2024-01-11 16:00:00',
            'access_level' => 'internal'
        ],
        [
            'id' => 10,
            'name' => 'Conformité et Qualité',
            'description' => 'Certificats, normes et documents de conformité',
            'icon' => 'fa-award',
            'color' => 'indigo',
            'documents_count' => 12,
            'total_size' => 2345678,
            'created_at' => '2023-02-20 13:45:00',
            'last_updated' => '2024-01-12 11:00:00',
            'access_level' => 'public'
        ]
    ],
    
    'categories' => [
        'Rapport' => ['icon' => 'fa-chart-bar', 'color' => 'blue'],
        'Contrat' => ['icon' => 'fa-handshake', 'color' => 'green'],
        'Plan' => ['icon' => 'fa-drafting-compass', 'color' => 'purple'],
        'Procédure' => ['icon' => 'fa-list-check', 'color' => 'yellow'],
        'Budget' => ['icon' => 'fa-coins', 'color' => 'orange'],
        'Correspondance' => ['icon' => 'fa-envelope', 'color' => 'gray'],
        'Technique' => ['icon' => 'fa-wrench', 'color' => 'indigo'],
        'Facture' => ['icon' => 'fa-file-invoice', 'color' => 'green'],
        'Demande' => ['icon' => 'fa-paper-plane', 'color' => 'blue'],
        'Devis' => ['icon' => 'fa-calculator', 'color' => 'orange'],
        'PV' => ['icon' => 'fa-gavel', 'color' => 'purple'],
        'Certificat' => ['icon' => 'fa-award', 'color' => 'gold']
    ],
    
    'status' => [
        'draft' => ['label' => 'Brouillon', 'color' => 'gray', 'icon' => 'fa-edit'],
        'pending' => ['label' => 'En attente', 'color' => 'yellow', 'icon' => 'fa-clock'],
        'pending_validation' => ['label' => 'En validation', 'color' => 'orange', 'icon' => 'fa-hourglass-half'],
        'validated' => ['label' => 'Validé', 'color' => 'green', 'icon' => 'fa-check-circle'],
        'archived' => ['label' => 'Archivé', 'color' => 'blue', 'icon' => 'fa-archive'],
        'rejected' => ['label' => 'Rejeté', 'color' => 'red', 'icon' => 'fa-times-circle']
    ],
    
    'confidentiality_levels' => [
        'public' => ['label' => 'Public', 'color' => 'green', 'description' => 'Accessible à tous'],
        'internal' => ['label' => 'Interne', 'color' => 'blue', 'description' => 'Accès interne uniquement'],
        'personnel' => ['label' => 'Personnel', 'color' => 'purple', 'description' => 'Données personnelles protégées'],
        'restricted' => ['label' => 'Restreint', 'color' => 'yellow', 'description' => 'Accès sur autorisation'],
        'confidential' => ['label' => 'Confidentiel', 'color' => 'red', 'description' => 'Accès très restreint']
    ]
]; 